spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest-api-database
    username: root
    password: admin12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
<<<<<<< HEAD
    show-sql: true
spring-doc:
      pathsToMatch: /person/**
      swagger-ui:
          use-root-path: true
=======
    show-sql: true
>>>>>>> bcfade803a03f53f19aadd85c2da2a592b794523
